name: test
run-name: test-test

defaults:
  run:
    shell: bash

on: 
  workflow_dispatch:
    inputs:
      language:
        description: "input here your languge"
        required: true
        type: string 

jobs:
  use-metafile-yaml-for-test:
    name: job test
    runs-on: ubuntu-latest
    outputs:
      lang: ${{ steps.output-language.outputs.echo-language }}
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: testeeeee
        run: ls -lah

      - id: output-language
        uses: ./
        with:
          hello-world-input: ${{ inputs.language }}

      - name: use inside job the output
        run: echo "the lang typed was $LANGUAGE_GOT"
        env:
          LANGUAGE_GOT: ${{ steps.output-language.outputs.echo-language }}

  use-language-got-inside-job:
    name: just a print
    needs: [use-metafile-yaml-for-test]
    runs-on: ubuntu-latest
    steps:
      - name: printing language
        run: echo $LANGUAGE
        env:
          LANGUAGE: ${{ needs.use-metafile-yaml-for-test.outputs.lang }}
